### ISSUE TITLE
UBUNTU INSTALLATION FAILED

### ISSUE THREAD

**Issue by ujjawalcse** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#35]
While running `python3.5 setup.py build_ext`
the following error occurred 
python version - 3.5 , 3.7 (tested at both versions)
cmake - 3.16.2
opencv version - 4.4.0 (installed with pip)

```
running build_ext
CMake Error at CMakeLists.txt:16 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "4.2.0.32".

  The following configuration files were considered but not accepted:

    /usr/share/OpenCV/OpenCVConfig.cmake, version: 3.2.0



-- Configuring incomplete, errors occurred!
See also "/home/ujjawal/my_work/motion_tracking3D/lightweight-human-pose-estimation-3d/pose_extractor/build/tmp/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    cmdclass={'build_ext': CMakeBuild})
  File "/home/ujjawal/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/ujjawal/.local/lib/python3.5/site-packages/setuptools/_distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ujjawal/.local/lib/python3.5/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/ujjawal/.local/lib/python3.5/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/ujjawal/.local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/home/ujjawal/.local/lib/python3.5/site-packages/setuptools/_distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 63, in build_extensions
    subprocess.check_call(['cmake', ext.cmake_lists_dir] + cmake_args, cwd=tmp_dir)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ujjawal/my_work/motion_tracking3D/lightweight-human-pose-estimation-3d/pose_extractor', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/home/ujjawal/my_work/motion_tracking3D/lightweight-human-pose-estimation-3d/pose_extractor/build', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=/home/ujjawal/my_work/motion_tracking3D/lightweight-human-pose-estimation-3d/pose_extractor/build/tmp', '-DPYTHON_EXECUTABLE=/usr/bin/python3.5']' returned non-zero exit status 1
```

**Comment by ujjawalcse** [comment]
Resolved the issue for my use case atleast.
I had opencv-python 4.2.0.32 installed with pip. So there is no corresponding OpenCVConfig.cmake file.
I changed the line no. 16 as` find_package(OpenCV 3 REQUIRED)`
