### ISSUE TITLE
Linux installation Issue 

### ISSUE THREAD

**Issue by sepidsh** [Daniil-Osokin/lightweight-human-pose-estimation-3d-demo.pytorch#4]
Hi, 
When I run "python setup.py build_ext"
I got this error:
-- Configuring incomplete, errors occurred!
See also "/local-scratch/sepid/lightweight-human-pose-estimation-3d-demo.pytorch/pose_extractor/build/tmp/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    cmdclass={'build_ext': CMakeBuild})
  File "/local-scratch/anaconda/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/local-scratch/anaconda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/local-scratch/anaconda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/local-scratch/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/local-scratch/anaconda/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/local-scratch/anaconda/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/local-scratch/anaconda/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 63, in build_extensions
    subprocess.check_call(['cmake', ext.cmake_lists_dir] + cmake_args, cwd=tmp_dir)
  File "/local-scratch/anaconda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/local-scratch/sepid/lightweight-human-pose-estimation-3d-demo.pytorch/pose_extractor', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/local-scratch/sepid/lightweight-human-pose-estimation-3d-demo.pytorch/pose_extractor/build', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=/local-scratch/sepid/lightweight-human-pose-estimation-3d-demo.pytorch/pose_extractor/build/tmp', '-DPYTHON_EXECUTABLE=/local-scratch/anaconda/bin/python']' returned non-zero exit status 1.

Do you have any Idea what is the problem?

**Comment by Daniil-Osokin** [comment]
Hi! This says, that error happened during `cmake` invocation, the real error should be above the line `-- Configuring incomplete, errors occurred!`. Will you post the full log?

**Comment by Daniil-Osokin** [comment]
Feel free to reopen with error description.
